messages:
  player-only: "This command can only be executed by players."
  usage: "&cUsage: /sks [item] (flags)."
  missing-flags: "&cMissing enchant. /sks [item] [enchant]"
  item-not-found: "&cThat item does not exist."
  shopkeeper-not-found: "&cCould not find a shopkeeper selling %item%(s)."
  out-of-stock: "&c&l[OUT OF STOCK]"
  # Line that gets sent to separate shopkeeper info if multiple found
  separator: "&8&m                                                 "
  # %stocked% - displays out-of-stock message if shop has no stock
  # %owner% - username of owner
  # %x%, %y%, %z% - coordinates of shopkeeper
  # %trade% - info about trade (such as 1x Diamond → 1x Emerald)
  # %item% - the item being searched
  shopkeeper-info: |
    %stocked%
    &2&lOwner: &a%owner%
    &2&lLocation: &aX: %x%, Y: %y%, Z: %z%
    &2&lTrade: &a%trade%

# The radius to search for shopkeepers
search-radius: 50.0