# This workflow will build a Java project with Gradle, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: build/libs/shopkeeper-search-1.1-SNAPSHOT.jar
          name: Release
          tag_name: 1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
